### Create profile /profiles/signup
POST http://127.0.0.1:5000/profiles/signup
Content-Type: application/json

{
    "username": "bandile@gmail.com",
    "password": "1234567890",
    "firstName": "Bandile",
    "lastName": "Danxa",
    "dateOfBirth": "12/05/1997",
    "gender": "male",
    "profilePhoto": "./images/bandile-profile.jpg",
    "coverPhoto": "./images/bandile-cover.jpg",
    "biography": "Smooth seas do not make good sailors",
    "joined": "2012",
    "relationshipStatus": "single"
}
###Get all profiles that are in the database /profiles/:id
GET http://127.0.0.1:5000/profiles
Content-Type: application/json

###Get profile by id /profiles/:id
GET http://localhost:5000/profiles/65aed6d2082122cc1df04c33
Content-Type: application/json

###Edit profile by id /profiles/update/:id
PUT http://localhost:5000/profiles/update/65aed6d2082122cc1df04c33
Content-Type: application/json

{
    "username": "athula@gmail.com",
    "password": "1234567890",
    "firstName": "Thulas",
    "lastName": "Sweetie",
    "profilePhoto": "./images/athula-profile.jpg",
    "coverPhoto": "./images/athula-cover.jpg",
    "biography": "I've got a dream and commited to defending it...",
    "joined": "2012",
    "relationshipStatus": "single"
}

###Delete profile by id /profiles/:id
DELETE http://localhost:5000/profiles/65aee1f2765b8a86ca1b26a2

/////////////////////////////////////////////////////////////////
### Create post /posts/create
POST http://localhost:5000/posts/add
Content-Type: application/json

{
    "postOwner": "Thulas Sweetie",
    "postOwnerProfilePhoto": "/images/athula-profile.jpg",
    "timePosted": "50",
    "privacy": "friends",
    "caption": "Degree bagged",
    "files": "/images/athula1.jpg",
    "reactions": 100,
    "comments": 5,
    "shares": 6
}

###Get all posts that are in the database /api/posts
GET http://localhost:5000/posts
Content-Type: application/json

###Get post by id /posts/:id
GET http://localhost:5000/posts/65aede541051fcac7209e49c
Content-Type: application/json

###Edit post by id /posts/:id
PUT http://localhost:5000/posts/65aede541051fcac7209e49c
Content-Type: application/json

{
    "postOwner": "Thulas Sweetie",
    "postOwnerProfilePhoto": "/images/athula-profile.jpg",
    "timePosted": "50",
    "privacy": "friends",
    "caption": "Beautiful day at the beach",
    "files": "/images/athula1.jpg",
    "reactions": 100,
    "comments": "Cute...",
    "shares": 6
}

###Delete post by id /posts/:id
DELETE http://localhost:5000/posts/65aede541051fcac7209e49c
Content-Type: application/json